### ISSUE TITLE
jaxlib==0.1.69+cuda111 still here and generating errors

### ISSUE THREAD

**Issue by ocstx** [kalininalab/alphafold_non_docker#52]
this line:
pip install --upgrade jax==0.2.14 jaxlib==0.1.69+cuda111 -f https://storage.googleapis.com/jax-releases/jax_releases.html
generates an error
this issue was solved here:
https://github.com/deepmind/alphafold/issues/510
with this:
pip install --upgrade jax==0.2.14 jaxlib==0.1.69+cuda111 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

Shuld not be changed?

**Comment by sanjaysrikakulam** [comment]
Sorry for the delay. It's fixed now via a pull request from @SarahBeecroft

**Comment by dahaigui** [comment]
I tried pip install --upgrade jax==0.2.14 jaxlib==0.1.69+cuda111 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html, but it doesn't work, There is still an error reported as 
“**AttributeError: module 'jaxlib.xla_extension' has no attribute 'CompiledFunction'**”
